version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: CargoGo.Api/Dockerfile
    container_name: cargogo-backend
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: cargogo-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped


